import type { MonthRecord } from './types';

// Historical bill data extracted from T-Mobile.xlsx
// Per-person amounts represent what each person owes for that month
export const HISTORY: MonthRecord[] = [
  // ── 2025 ──────────────────────────────────────────────────────────────────
  {
    month: '2025-01',
    totalBill: 356.82,
    verified: true,
    verifiedTotal: 356.80,
    savedAt: '2025-01-31',
    notes: 'Jan 2025',
    personShares: [
      { name: 'Saket (Me)', accountGroup: 'saket', lines: ['Saket'], lineCharges: 88.83, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 88.83, paid: 0, balance: 88.83 },
      { name: 'Dari / Sanjay', accountGroup: 'dari', lines: ['Sanjay'], lineCharges: 33.83, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 33.83, paid: 0, balance: 33.83 },
      { name: 'Saroj / Ritesh', accountGroup: 'saroj', lines: ['Saroj', 'Ritesh'], lineCharges: 63.83, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 63.83, paid: 0, balance: 63.83 },
      { name: 'Chiranjiwi', accountGroup: 'chiranjiwi', lines: ['Chiranjiwi'], lineCharges: 33.83, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 33.83, paid: 0, balance: 33.83 },
      { name: 'Mainali', accountGroup: 'mainali', lines: ['Bikas'], lineCharges: 35.99, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 35.99, paid: 0, balance: 35.99 },
      { name: 'Bajpayee', accountGroup: 'bajpayee', lines: ['Bajpayee', 'Sapana iPhone'], lineCharges: 100.49, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 100.49, paid: 0, balance: 100.49 },
    ],
  },
  {
    month: '2025-02',
    totalBill: 356.82,
    verified: true,
    verifiedTotal: 356.80,
    savedAt: '2025-02-28',
    notes: 'Feb 2025',
    personShares: [
      { name: 'Saket (Me)', accountGroup: 'saket', lines: ['Saket'], lineCharges: 88.83, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 88.83, paid: 0, balance: 88.83 },
      { name: 'Dari / Sanjay', accountGroup: 'dari', lines: ['Sanjay'], lineCharges: 33.83, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 33.83, paid: 0, balance: 33.83 },
      { name: 'Saroj / Ritesh', accountGroup: 'saroj', lines: ['Saroj', 'Ritesh'], lineCharges: 63.83, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 63.83, paid: 0, balance: 63.83 },
      { name: 'Chiranjiwi', accountGroup: 'chiranjiwi', lines: ['Chiranjiwi'], lineCharges: 33.83, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 33.83, paid: 0, balance: 33.83 },
      { name: 'Mainali', accountGroup: 'mainali', lines: ['Bikas'], lineCharges: 35.99, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 35.99, paid: 0, balance: 35.99 },
      { name: 'Bajpayee', accountGroup: 'bajpayee', lines: ['Bajpayee', 'Sapana iPhone'], lineCharges: 100.49, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 100.49, paid: 0, balance: 100.49 },
    ],
  },
  {
    month: '2025-03',
    totalBill: 356.82,
    verified: true,
    verifiedTotal: 356.80,
    savedAt: '2025-03-31',
    notes: 'Mar 2025',
    personShares: [
      { name: 'Saket (Me)', accountGroup: 'saket', lines: ['Saket'], lineCharges: 88.83, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 88.83, paid: 0, balance: 88.83 },
      { name: 'Dari / Sanjay', accountGroup: 'dari', lines: ['Sanjay'], lineCharges: 33.83, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 33.83, paid: 0, balance: 33.83 },
      { name: 'Saroj / Ritesh', accountGroup: 'saroj', lines: ['Saroj', 'Ritesh'], lineCharges: 63.83, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 63.83, paid: 0, balance: 63.83 },
      { name: 'Chiranjiwi', accountGroup: 'chiranjiwi', lines: ['Chiranjiwi'], lineCharges: 33.83, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 33.83, paid: 0, balance: 33.83 },
      { name: 'Mainali', accountGroup: 'mainali', lines: ['Bikas'], lineCharges: 35.99, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 35.99, paid: 0, balance: 35.99 },
      { name: 'Bajpayee', accountGroup: 'bajpayee', lines: ['Bajpayee', 'Sapana iPhone'], lineCharges: 100.49, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 100.49, paid: 0, balance: 100.49 },
    ],
  },
  {
    month: '2025-04',
    totalBill: 407.23,
    verified: true,
    verifiedTotal: 407.21,
    savedAt: '2025-04-30',
    notes: 'Apr 2025 – plan price increased $5 for all lines',
    personShares: [
      { name: 'Saket (Me)', accountGroup: 'saket', lines: ['Saket'], lineCharges: 93.83, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 93.83, paid: 0, balance: 93.83 },
      { name: 'Dari / Sanjay', accountGroup: 'dari', lines: ['Sanjay'], lineCharges: 38.83, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 38.83, paid: 0, balance: 38.83 },
      { name: 'Saroj / Ritesh', accountGroup: 'saroj', lines: ['Saroj', 'Ritesh'], lineCharges: 84.24, sharedCostShare: 0, credits: 0, extras: 10.41, previousDue: 0, total: 84.24, paid: 0, balance: 84.24, notes: 'Ritesh roaming $10.41' },
      { name: 'Chiranjiwi', accountGroup: 'chiranjiwi', lines: ['Chiranjiwi'], lineCharges: 38.83, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 38.83, paid: 0, balance: 38.83 },
      { name: 'Mainali', accountGroup: 'mainali', lines: ['Bikas'], lineCharges: 40.99, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 40.99, paid: 0, balance: 40.99 },
      { name: 'Bajpayee', accountGroup: 'bajpayee', lines: ['Bajpayee', 'Sapana iPhone'], lineCharges: 110.49, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 110.49, paid: 0, balance: 110.49 },
    ],
  },
  {
    month: '2025-05',
    totalBill: 407.23,
    verified: true,
    verifiedTotal: 407.21,
    savedAt: '2025-05-31',
    notes: 'May 2025',
    personShares: [
      { name: 'Saket (Me)', accountGroup: 'saket', lines: ['Saket'], lineCharges: 93.83, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 93.83, paid: 0, balance: 93.83 },
      { name: 'Dari / Sanjay', accountGroup: 'dari', lines: ['Sanjay'], lineCharges: 38.83, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 38.83, paid: 0, balance: 38.83 },
      { name: 'Saroj / Ritesh', accountGroup: 'saroj', lines: ['Saroj', 'Ritesh'], lineCharges: 73.66, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 73.66, paid: 0, balance: 73.66 },
      { name: 'Chiranjiwi', accountGroup: 'chiranjiwi', lines: ['Chiranjiwi'], lineCharges: 38.83, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 38.83, paid: 0, balance: 38.83 },
      { name: 'Mainali', accountGroup: 'mainali', lines: ['Bikas'], lineCharges: 40.99, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 40.99, paid: 0, balance: 40.99 },
      { name: 'Bajpayee', accountGroup: 'bajpayee', lines: ['Bajpayee', 'Sapana iPhone'], lineCharges: 110.49, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 110.49, paid: 0, balance: 110.49 },
    ],
  },
  {
    month: '2025-06',
    totalBill: 672.27,
    verified: true,
    verifiedTotal: 672.26,
    savedAt: '2025-06-30',
    notes: 'Jun 2025 – iPhone 16 upgrades; full equipment costs before credits applied',
    personShares: [
      { name: 'Saket (Me)', accountGroup: 'saket', lines: ['Saket', 'Saket iPhone'], lineCharges: 166.69, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 166.69, paid: 0, balance: 166.69 },
      { name: 'Dari / Sanjay', accountGroup: 'dari', lines: ['Sanjay', 'Dari iPhone'], lineCharges: 80.09, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 80.09, paid: 0, balance: 80.09 },
      { name: 'Saroj / Ritesh', accountGroup: 'saroj', lines: ['Saroj', 'Ritesh', 'Saroj iPhone'], lineCharges: 73.01, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 73.01, paid: 0, balance: 73.01 },
      { name: 'Chiranjiwi', accountGroup: 'chiranjiwi', lines: ['Chiranjiwi'], lineCharges: 59.05, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 59.05, paid: 0, balance: 59.05 },
      { name: 'Mainali', accountGroup: 'mainali', lines: ['Bikas', 'Mainali iPhone'], lineCharges: 61.21, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 61.21, paid: 0, balance: 61.21 },
      { name: 'Bajpayee', accountGroup: 'bajpayee', lines: ['Bajpayee', 'Sapana iPhone', 'Bajpayee iPhone'], lineCharges: 176.97, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 176.97, paid: 0, balance: 176.97 },
    ],
  },
  {
    month: '2025-07',
    totalBill: 565.51,
    verified: true,
    verifiedTotal: 565.51,
    savedAt: '2025-07-31',
    paidBy: 'Sanjay',
    notes: 'Jul 2025 – credits applied: Sanjay $225, Saket $255, Saroj/Ritesh $305, Mainali $135',
    personShares: [
      { name: 'Saket (Me)', accountGroup: 'saket', lines: ['Saket', 'Saket iPhone'], lineCharges: 91.69, sharedCostShare: 0, credits: 255, extras: 0, previousDue: 0, total: 91.69, paid: 0, balance: 91.69 },
      { name: 'Dari / Sanjay', accountGroup: 'dari', lines: ['Sanjay', 'Dari iPhone'], lineCharges: 80.09, sharedCostShare: 0, credits: 225, extras: 0, previousDue: 0, total: 80.09, paid: 0, balance: 80.09 },
      { name: 'Saroj / Ritesh', accountGroup: 'saroj', lines: ['Saroj', 'Ritesh', 'Saroj iPhone'], lineCharges: 73.01, sharedCostShare: 0, credits: 305, extras: 0.75, previousDue: 0, total: 73.01, paid: 0, balance: 73.01, notes: 'Mama roaming $0.75' },
      { name: 'Chiranjiwi', accountGroup: 'chiranjiwi', lines: ['Chiranjiwi'], lineCharges: 59.80, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 59.80, paid: 0, balance: 59.80 },
      { name: 'Mainali', accountGroup: 'mainali', lines: ['Bikas', 'Mainali iPhone'], lineCharges: 61.21, sharedCostShare: 0, credits: 135, extras: 0, previousDue: 0, total: 61.21, paid: 0, balance: 61.21 },
      { name: 'Bajpayee', accountGroup: 'bajpayee', lines: ['Bajpayee', 'Sapana iPhone', 'Bajpayee iPhone'], lineCharges: 144.46, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 144.46, paid: 0, balance: 144.46 },
    ],
  },
  {
    month: '2025-08',
    totalBill: 575.10,
    verified: false,
    verifiedTotal: 0,
    savedAt: '2025-08-31',
    paidBy: 'Sanjay',
    notes: 'Aug 2025 – estimated based on plan structure',
    personShares: [
      { name: 'Saket (Me)', accountGroup: 'saket', lines: ['Saket', 'Saket iPhone'], lineCharges: 91.69, sharedCostShare: 0, credits: 23.06, extras: 0, previousDue: 0, total: 68.63, paid: 0, balance: 68.63 },
      { name: 'Dari / Sanjay', accountGroup: 'dari', lines: ['Sanjay', 'Dari iPhone'], lineCharges: 80.09, sharedCostShare: 0, credits: 23.06, extras: 0, previousDue: 0, total: 57.03, paid: 0, balance: 57.03 },
      { name: 'Saroj / Ritesh', accountGroup: 'saroj', lines: ['Saroj', 'Ritesh', 'Saroj iPhone'], lineCharges: 73.01, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 73.01, paid: 0, balance: 73.01 },
      { name: 'Chiranjiwi', accountGroup: 'chiranjiwi', lines: ['Chiranjiwi'], lineCharges: 59.80, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 59.80, paid: 0, balance: 59.80 },
      { name: 'Mainali', accountGroup: 'mainali', lines: ['Bikas', 'Mainali iPhone'], lineCharges: 61.21, sharedCostShare: 0, credits: 17.50, extras: 0, previousDue: 0, total: 43.71, paid: 0, balance: 43.71 },
      { name: 'Bajpayee', accountGroup: 'bajpayee', lines: ['Bajpayee', 'Sapana iPhone', 'Bajpayee iPhone'], lineCharges: 144.46, sharedCostShare: 0, credits: 35.56, extras: 0, previousDue: 0, total: 108.90, paid: 0, balance: 108.90 },
    ],
  },
  // Sep–Dec 2025: Experience Beyond plan, 7 standard voice lines + Sapana + HomeInternet
  // AccountShare = AccountLevel / 7; Chiranjiwi group includes Dadha Router ($61.60/mo)
  // Bajpayee group includes Sapana's line (net after her promo credit already in bill)
  // Sanjay pays T-Mobile bill from Jul 2025 onwards
  {
    month: '2025-09',
    totalBill: 534.91,
    verified: true,
    verifiedTotal: 534.90,
    savedAt: '2025-09-24',
    paidBy: 'Sanjay',
    notes: 'Sep 2025 – verified from PDF bill',
    personShares: [
      { name: 'Dari / Sanjay', accountGroup: 'dari', lines: ['Sanjay'], lineCharges: 71.24, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 71.24, paid: 0, balance: 71.24 },
      { name: 'Saket (Me)', accountGroup: 'saket', lines: ['Saket'], lineCharges: 71.24, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 71.24, paid: 0, balance: 71.24 },
      { name: 'Saroj / Ritesh', accountGroup: 'saroj', lines: ['Saroj', 'Ritesh'], lineCharges: 114.36, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 114.36, paid: 0, balance: 114.36 },
      { name: 'Chiranjiwi', accountGroup: 'chiranjiwi', lines: ['Chiranjiwi', 'Dadha Router'], lineCharges: 111.80, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 111.80, paid: 0, balance: 111.80 },
      { name: 'Mainali', accountGroup: 'mainali', lines: ['Bikas'], lineCharges: 52.36, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 52.36, paid: 0, balance: 52.36 },
      { name: 'Bajpayee', accountGroup: 'bajpayee', lines: ['Bajpayee', 'Sapana'], lineCharges: 113.90, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 113.90, paid: 0, balance: 113.90 },
    ],
  },
  {
    month: '2025-10',
    totalBill: 534.97,
    verified: true,
    verifiedTotal: 534.98,
    savedAt: '2025-10-24',
    paidBy: 'Sanjay',
    notes: 'Oct 2025 – verified from PDF bill',
    personShares: [
      { name: 'Dari / Sanjay', accountGroup: 'dari', lines: ['Sanjay'], lineCharges: 71.25, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 71.25, paid: 0, balance: 71.25 },
      { name: 'Saket (Me)', accountGroup: 'saket', lines: ['Saket'], lineCharges: 71.25, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 71.25, paid: 0, balance: 71.25 },
      { name: 'Saroj / Ritesh', accountGroup: 'saroj', lines: ['Saroj', 'Ritesh'], lineCharges: 114.38, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 114.38, paid: 0, balance: 114.38 },
      { name: 'Chiranjiwi', accountGroup: 'chiranjiwi', lines: ['Chiranjiwi', 'Dadha Router'], lineCharges: 111.81, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 111.81, paid: 0, balance: 111.81 },
      { name: 'Mainali', accountGroup: 'mainali', lines: ['Bikas'], lineCharges: 52.37, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 52.37, paid: 0, balance: 52.37 },
      { name: 'Bajpayee', accountGroup: 'bajpayee', lines: ['Bajpayee', 'Sapana'], lineCharges: 113.92, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 113.92, paid: 0, balance: 113.92 },
    ],
  },
  {
    month: '2025-11',
    totalBill: 575.23,
    verified: true,
    verifiedTotal: 575.21,
    savedAt: '2025-11-24',
    paidBy: 'Sanjay',
    notes: 'Nov 2025 – elevated account charges ($351.84 vs ~$316 normal); Sapana higher at $42.69',
    personShares: [
      { name: 'Dari / Sanjay', accountGroup: 'dari', lines: ['Sanjay'], lineCharges: 76.28, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 76.28, paid: 0, balance: 76.28 },
      { name: 'Saket (Me)', accountGroup: 'saket', lines: ['Saket'], lineCharges: 76.28, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 76.28, paid: 0, balance: 76.28 },
      { name: 'Saroj / Ritesh', accountGroup: 'saroj', lines: ['Saroj', 'Ritesh'], lineCharges: 124.44, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 124.44, paid: 0, balance: 124.44 },
      { name: 'Chiranjiwi', accountGroup: 'chiranjiwi', lines: ['Chiranjiwi', 'Dadha Router'], lineCharges: 116.84, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 116.84, paid: 0, balance: 116.84 },
      { name: 'Mainali', accountGroup: 'mainali', lines: ['Bikas'], lineCharges: 57.40, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 57.40, paid: 0, balance: 57.40 },
      { name: 'Bajpayee', accountGroup: 'bajpayee', lines: ['Bajpayee', 'Sapana'], lineCharges: 123.97, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 123.97, paid: 0, balance: 123.97, notes: 'Sapana $42.69 (higher than usual)' },
    ],
  },
  {
    month: '2025-12',
    totalBill: 535.01,
    verified: true,
    verifiedTotal: 534.98,
    savedAt: '2025-12-24',
    paidBy: 'Sanjay',
    notes: 'Dec 2025 – verified from PDF bill',
    personShares: [
      { name: 'Dari / Sanjay', accountGroup: 'dari', lines: ['Sanjay'], lineCharges: 71.25, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 71.25, paid: 0, balance: 71.25 },
      { name: 'Saket (Me)', accountGroup: 'saket', lines: ['Saket'], lineCharges: 71.25, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 71.25, paid: 0, balance: 71.25 },
      { name: 'Saroj / Ritesh', accountGroup: 'saroj', lines: ['Saroj', 'Ritesh'], lineCharges: 114.38, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 114.38, paid: 0, balance: 114.38 },
      { name: 'Chiranjiwi', accountGroup: 'chiranjiwi', lines: ['Chiranjiwi', 'Dadha Router'], lineCharges: 111.81, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 111.81, paid: 0, balance: 111.81 },
      { name: 'Mainali', accountGroup: 'mainali', lines: ['Bikas'], lineCharges: 52.37, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 52.37, paid: 0, balance: 52.37 },
      { name: 'Bajpayee', accountGroup: 'bajpayee', lines: ['Bajpayee', 'Sapana'], lineCharges: 113.92, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 113.92, paid: 0, balance: 113.92 },
    ],
  },
  // ── 2026 ──────────────────────────────────────────────────────────────────
  // Jan 2026+: new voice line (701) 412-4006 added Jan 19, 2026 (identity unknown)
  // AccountShare = AccountLevel / 8 (8 standard voice lines)
  {
    month: '2026-01',
    totalBill: 648.02,
    verified: true,
    verifiedTotal: 648.05,
    savedAt: '2026-01-24',
    paidBy: 'Sanjay',
    notes: 'Jan 2026 – new voice line (701) 412-4006 added Jan 19 (iPhone 17 Pro partial month); Regulatory Programs fee +$0.50/line',
    personShares: [
      { name: 'Dari / Sanjay', accountGroup: 'dari', lines: ['Sanjay'], lineCharges: 66.51, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 66.51, paid: 0, balance: 66.51 },
      { name: 'Saket (Me)', accountGroup: 'saket', lines: ['Saket'], lineCharges: 66.51, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 66.51, paid: 0, balance: 66.51 },
      { name: 'Saroj / Ritesh', accountGroup: 'saroj', lines: ['Saroj', 'Ritesh'], lineCharges: 104.90, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 104.90, paid: 0, balance: 104.90 },
      { name: 'Chiranjiwi', accountGroup: 'chiranjiwi', lines: ['Chiranjiwi', 'Dadha Router'], lineCharges: 107.57, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 107.57, paid: 0, balance: 107.57 },
      { name: 'Mainali', accountGroup: 'mainali', lines: ['Bikas'], lineCharges: 47.63, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 47.63, paid: 0, balance: 47.63 },
      { name: 'Bajpayee', accountGroup: 'bajpayee', lines: ['Bajpayee', 'Sapana'], lineCharges: 109.71, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 109.71, paid: 0, balance: 109.71 },
      { name: 'New Line (701)', accountGroup: 'newline', lines: ['NewLine'], lineCharges: 145.22, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 145.22, paid: 0, balance: 145.22, notes: 'Partial month + iPhone 17 Pro EIP $33.54/mo' },
    ],
  },
  {
    month: '2026-02',
    totalBill: 639.03,
    verified: true,
    verifiedTotal: 639.06,
    savedAt: '2026-02-24',
    paidBy: 'Sanjay',
    notes: 'Feb 2026 – verified from PDF bill',
    personShares: [
      { name: 'Dari / Sanjay', accountGroup: 'dari', lines: ['Sanjay'], lineCharges: 66.51, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 66.51, paid: 0, balance: 66.51 },
      { name: 'Saket (Me)', accountGroup: 'saket', lines: ['Saket'], lineCharges: 66.51, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 66.51, paid: 0, balance: 66.51 },
      { name: 'Saroj / Ritesh', accountGroup: 'saroj', lines: ['Saroj', 'Ritesh'], lineCharges: 104.90, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 104.90, paid: 0, balance: 104.90 },
      { name: 'Chiranjiwi', accountGroup: 'chiranjiwi', lines: ['Chiranjiwi', 'Dadha Router'], lineCharges: 107.57, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 107.57, paid: 0, balance: 107.57 },
      { name: 'Mainali', accountGroup: 'mainali', lines: ['Bikas'], lineCharges: 47.63, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 47.63, paid: 0, balance: 47.63 },
      { name: 'Bajpayee', accountGroup: 'bajpayee', lines: ['Bajpayee', 'Sapana'], lineCharges: 109.71, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 109.71, paid: 0, balance: 109.71 },
      { name: 'New Line (701)', accountGroup: 'newline', lines: ['NewLine'], lineCharges: 136.23, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 136.23, paid: 0, balance: 136.23, notes: 'iPhone 17 Pro EIP $33.54/mo' },
    ],
  },
  {
    month: '2026-03',
    totalBill: 640.40,
    verified: true,
    verifiedTotal: 640.43,
    savedAt: '2026-03-24',
    paidBy: 'Sanjay',
    notes: 'Mar 2026 – Ritesh extra equipment charge this month',
    personShares: [
      { name: 'Dari / Sanjay', accountGroup: 'dari', lines: ['Sanjay'], lineCharges: 66.51, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 66.51, paid: 0, balance: 66.51 },
      { name: 'Saket (Me)', accountGroup: 'saket', lines: ['Saket'], lineCharges: 66.51, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 66.51, paid: 0, balance: 66.51 },
      { name: 'Saroj / Ritesh', accountGroup: 'saroj', lines: ['Saroj', 'Ritesh'], lineCharges: 111.74, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 111.74, paid: 0, balance: 111.74, notes: 'Ritesh extra equipment $6.84' },
      { name: 'Chiranjiwi', accountGroup: 'chiranjiwi', lines: ['Chiranjiwi', 'Dadha Router'], lineCharges: 107.57, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 107.57, paid: 0, balance: 107.57 },
      { name: 'Mainali', accountGroup: 'mainali', lines: ['Bikas'], lineCharges: 47.63, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 47.63, paid: 0, balance: 47.63 },
      { name: 'Bajpayee', accountGroup: 'bajpayee', lines: ['Bajpayee', 'Sapana'], lineCharges: 109.71, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 109.71, paid: 0, balance: 109.71 },
      { name: 'New Line (701)', accountGroup: 'newline', lines: ['NewLine'], lineCharges: 130.76, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 130.76, paid: 0, balance: 130.76, notes: 'iPhone 17 Pro EIP $33.54/mo' },
    ],
  },
  {
    month: '2026-04',
    totalBill: 645.97,
    verified: true,
    verifiedTotal: 645.98,
    savedAt: '2026-04-24',
    paidBy: 'Sanjay',
    notes: 'Apr 2026 – Sapana higher charge ($50.69, Sapana promo credit may not have applied)',
    personShares: [
      { name: 'Dari / Sanjay', accountGroup: 'dari', lines: ['Sanjay'], lineCharges: 66.50, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 66.50, paid: 0, balance: 66.50 },
      { name: 'Saket (Me)', accountGroup: 'saket', lines: ['Saket'], lineCharges: 66.50, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 66.50, paid: 0, balance: 66.50 },
      { name: 'Saroj / Ritesh', accountGroup: 'saroj', lines: ['Saroj', 'Ritesh'], lineCharges: 104.88, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 104.88, paid: 0, balance: 104.88 },
      { name: 'Chiranjiwi', accountGroup: 'chiranjiwi', lines: ['Chiranjiwi', 'Dadha Router'], lineCharges: 107.56, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 107.56, paid: 0, balance: 107.56 },
      { name: 'Mainali', accountGroup: 'mainali', lines: ['Bikas'], lineCharges: 47.62, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 47.62, paid: 0, balance: 47.62 },
      { name: 'Bajpayee', accountGroup: 'bajpayee', lines: ['Bajpayee', 'Sapana'], lineCharges: 122.19, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 122.19, paid: 0, balance: 122.19, notes: 'Sapana $50.69 (higher, credit may not apply)' },
      { name: 'New Line (701)', accountGroup: 'newline', lines: ['NewLine'], lineCharges: 130.73, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 130.73, paid: 0, balance: 130.73, notes: 'iPhone 17 Pro EIP $33.54/mo' },
    ],
  },
  {
    month: '2026-05',
    totalBill: 621.26,
    verified: true,
    verifiedTotal: 621.27,
    savedAt: '2026-05-24',
    paidBy: 'Sanjay',
    notes: 'May 2026 – Sapana lower charge ($25.69)',
    personShares: [
      { name: 'Dari / Sanjay', accountGroup: 'dari', lines: ['Sanjay'], lineCharges: 66.50, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 66.50, paid: 0, balance: 66.50 },
      { name: 'Saket (Me)', accountGroup: 'saket', lines: ['Saket'], lineCharges: 66.50, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 66.50, paid: 0, balance: 66.50 },
      { name: 'Saroj / Ritesh', accountGroup: 'saroj', lines: ['Saroj', 'Ritesh'], lineCharges: 104.88, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 104.88, paid: 0, balance: 104.88 },
      { name: 'Chiranjiwi', accountGroup: 'chiranjiwi', lines: ['Chiranjiwi', 'Dadha Router'], lineCharges: 107.56, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 107.56, paid: 0, balance: 107.56 },
      { name: 'Mainali', accountGroup: 'mainali', lines: ['Bikas'], lineCharges: 47.91, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 47.91, paid: 0, balance: 47.91 },
      { name: 'Bajpayee', accountGroup: 'bajpayee', lines: ['Bajpayee', 'Sapana'], lineCharges: 97.19, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 97.19, paid: 0, balance: 97.19, notes: 'Sapana $25.69 (lower this month)' },
      { name: 'New Line (701)', accountGroup: 'newline', lines: ['NewLine'], lineCharges: 130.73, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 130.73, paid: 0, balance: 130.73, notes: 'iPhone 17 Pro EIP $33.54/mo' },
    ],
  },
  // ── 2024 ──────────────────────────────────────────────────────────────────
  {
    month: '2024-01',
    totalBill: 406.14,
    verified: true,
    verifiedTotal: 406.14,
    savedAt: '2024-01-31',
    notes: 'Jan 2024',
    personShares: [
      { name: 'Saket (Me)', accountGroup: 'saket', lines: ['Saket'], lineCharges: 110.58, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 110.58, paid: 0, balance: 110.58 },
      { name: 'Dari / Sanjay', accountGroup: 'dari', lines: ['Sanjay'], lineCharges: 86.08, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 86.08, paid: 0, balance: 86.08 },
      { name: 'Saroj / Ritesh', accountGroup: 'saroj', lines: ['Saroj', 'Ritesh'], lineCharges: 70.83, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 70.83, paid: 0, balance: 70.83 },
      { name: 'Chiranjiwi', accountGroup: 'chiranjiwi', lines: ['Chiranjiwi'], lineCharges: 34.33, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 34.33, paid: 0, balance: 34.33 },
      { name: 'Mainali', accountGroup: 'mainali', lines: ['Bikas'], lineCharges: 40.33, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 40.33, paid: 0, balance: 40.33 },
      { name: 'Bajpayee', accountGroup: 'bajpayee', lines: ['Bajpayee'], lineCharges: 63.99, sharedCostShare: 0, credits: 0, extras: 0, previousDue: 0, total: 63.99, paid: 0, balance: 63.99 },
    ],
  },
];

export function getHistoryMonth(month: string): MonthRecord | undefined {
  return HISTORY.find((r) => r.month === month);
}

export function getRecentHistory(n = 12): MonthRecord[] {
  return [...HISTORY].sort((a, b) => b.month.localeCompare(a.month)).slice(0, n);
}
