/**
 * Per-line itemized breakdown data derived from T-Mobile PDF bills.
 * Used to enrich PersonShare objects with tap-to-expand detail.
 *
 * The JSON was generated by: scripts/generate_lineitems.py
 * Source PDFs: ~/Downloads/T-Mobile/DetailedBill*.pdf
 */

import type { PersonShare, PersonShareLineItem } from './types';
import rawLineItems from '../data/lineitems_by_month.json';

interface MonthGroupData {
  items: PersonShareLineItem[];
  phone_sum: number;
}

type LineItemsDB = Record<string, Record<string, MonthGroupData>>;

const LINE_ITEMS_DB = rawLineItems as LineItemsDB;

/**
 * Get itemized line items for one PersonShare.
 * Appends an "account plan share" entry if lineCharges > phone line totals.
 */
export function getLineItemsForShare(
  month: string,
  share: PersonShare
): PersonShareLineItem[] {
  const monthData = LINE_ITEMS_DB[month];
  if (!monthData) return [];

  const groupData = monthData[share.accountGroup];
  if (!groupData) return [];

  const { items, phone_sum } = groupData;
  const baseCharges = share.lineCharges + share.sharedCostShare;
  const accountShare = Math.round((baseCharges - phone_sum) * 100) / 100;

  const result: PersonShareLineItem[] = [...items];

  if (accountShare > 0.5) {
    result.push({
      label: 'Base plan share',
      sublabel: 'Shared account line allocation',
      amount: accountShare,
      kind: 'plan',
    });
  }

  return result;
}

/**
 * Enrich all PersonShares in a MonthRecord with lineItems from PDF data.
 * Returns a new array (does not mutate inputs).
 */
export function enrichPersonShares(
  month: string,
  shares: PersonShare[]
): PersonShare[] {
  return shares.map((share) => {
    const lineItems = getLineItemsForShare(month, share);
    if (lineItems.length === 0) return share;
    return { ...share, lineItems };
  });
}

/**
 * Check if PDF line item data exists for a given month.
 */
export function hasLineItemData(month: string): boolean {
  return month in LINE_ITEMS_DB;
}
